"""Reading and validating CIIM input files.

Everything downstream receives
validated, immutable objects, which is what lets the model run from the command
line, from a notebook, or from a GUI.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

import math

from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

# default input directory, defined relative to current file location
INPUTS_DIR = Path(__file__).resolve().parent / "inputs"


# Pydantic schemas, one per input file shape. Validation runs on construction,
# so a bad value fails here rather than surfacing as a wrong number later.


class Frozen(BaseModel):
    """Shared settings for every schema: immutable, and an unknown key is an error."""

    model_config = ConfigDict(frozen=True, extra="forbid")

class Forcing(Frozen):
    """The radiative effect of a deployed material, in material.yaml."""

    per_Tg_per_year: float = Field(gt=0, description="W/m2 per Tg/year injected")
    reference_lifetime_months: float = Field(
        gt=0, description="Residence time per_mass was calibrated at; only its ratio is used"
    )
    source: str


class Material(Frozen):
    """One entry in material.yaml."""

    cost: float = Field(ge=0, description="USD per kg of this material")
    source: str = Field(description="Where the cost figure came from")
    forcing: Forcing | None = None   # only a deployed material needs one


class SweepRange(Frozen):
    """An inclusive start/stop/step range of values for one swept parameter."""

    start: float
    stop: float
    step: float = Field(gt=0)

    @model_validator(mode="after")
    def stop_at_or_above_start(self) -> SweepRange: # error check in case parameter sweep starts after it stops
        if self.stop < self.start:
            raise ValueError(f"sweep stop ({self.stop}) is below start ({self.start})")
        return self

    @model_validator(mode="after")
    def step_divides_span(self) -> SweepRange: # error check
        """The span must be a whole number of steps, or the sweep isn't the one asked for.

        values() spaces its points evenly between start and stop, so a span that is
        not a whole multiple of step comes back with a different spacing than the
        YAML requested — silently.
        """
        span = self.stop - self.start
        n_steps = round(span / self.step)
        if not math.isclose(n_steps * self.step, span, rel_tol=1e-9): # a little bit of tolerance here in case of slight discrepancies in float numbers
            landed = self.start + n_steps * self.step
            raise ValueError(
                f"sweep step {self.step:g} does not divide {self.start:g}..{self.stop:g} "
                f"a whole number of times ({span / self.step:.6g} steps). "
                f"Set stop to {landed:g}, or pick a step that divides {span:g}."
            )
        return self

    
    def values(self) -> list[float]:
        """Endpoint-exact values, generated by count rather than accumulation.

        Assumes step_divides_span has passed.
        """
        n = round((self.stop - self.start) / self.step) + 1
        if n == 1:
            return [self.start]
        return [self.start + i * (self.stop - self.start) / (n - 1) for i in range(n)]


class Scenario(Frozen):
    """scenario.yaml: what the model is being asked to do."""

    deployment_method: str
    deployed_material: str
    altitude: float = Field(gt=0, description="Injection altitude, metres")

    # Exactly one of these two. deployment_pattern names the deployed masses
    # directly and skips climatology. temperature_pattern names a cooling
    # requirement for climatology to convert into masses, which needs a
    # latitude to inject at; an override pattern carries its own latitudes.
    deployment_pattern: str | None = None
    temperature_pattern: str | None = None
    latitude: int | None = Field(
        default=None, ge=0, le=90,
        description="Injection latitude, degrees; deployed half north and half south",
    )

    sweep: dict[str, SweepRange] = Field(default_factory=dict)
    # Numeric ranges only for now. Sweeping deployment_method or
    # deployment_pattern needs a list of strings, i.e. SweepRange | list[...].

    @model_validator(mode="after")
    def exactly_one_deployment_source(self) -> Scenario:
        if bool(self.deployment_pattern) == bool(self.temperature_pattern):
            raise ValueError(
                "name exactly one of deployment_pattern (deployed masses directly) "
                "or temperature_pattern (a cooling requirement for climatology)"
            )
        if self.temperature_pattern and self.latitude is None:
            raise ValueError("temperature_pattern needs a latitude to inject at")
        if self.deployment_pattern and self.latitude is not None:
            raise ValueError(
                "latitude is not used with deployment_pattern: an override pattern "
                "carries its own latitudes in its columns"
            )
        return self


class Climate(Frozen):
    """climate.yaml: the simplified climate representation."""

    cooling_per_forcing: dict[int, float] = Field(
        description="degC of global mean cooling per W/m2 of forcing, by injection latitude"
    )
    source: str
    stratospheric_lifetimes: str = Field(description="CSV in stratospheric_lifetimes/")

    @model_validator(mode="after")
    def latitudes_are_a_grid(self) -> Climate:
        if not self.cooling_per_forcing:
            raise ValueError("cooling_per_forcing needs at least one latitude")
        bad = [lat for lat in self.cooling_per_forcing if not 0 <= lat <= 90]
        if bad:
            raise ValueError(f"cooling_per_forcing latitudes must be 0-90 degrees; got {bad}")
        return self


@dataclass(frozen=True)
class Inputs:
    """Everything one model run needs, as a single value."""

    scenario: Scenario
    materials: dict[str, Material]
    currency_year: int
    pattern: pd.DataFrame        # kg/year, indexed by year, columns are latitudes
    method: dict[str, Any]       # raw method YAML; the method module validates it
    inputs_dir: Path             # where this set was loaded from

    # Climate mode only; all three are None when a deployment_pattern overrides
    # the climatology module.
    cooling_per_forcing: dict[int, float] | None = None   # degC per W/m2, by latitude
    lifetimes: pd.DataFrame | None = None                 # months, (season, altitude) x latitude
    temperature: pd.DataFrame | None = None               # degC anomalies, indexed by year
 
    def __post_init__(self) -> None:
        if self.scenario.deployed_material not in self.materials:
            raise ValueError(
                f"deployed_material {self.scenario.deployed_material!r} is not in "
                f"material.yaml. Known materials: {', '.join(sorted(self.materials))}"
            )

        # The scenario's either/or has to hold for the data too, or a climate-mode
        # run could reach climatology with nothing to compute from.
        loaded = [f is not None for f in
                  (self.cooling_per_forcing, self.lifetimes, self.temperature)]
        if self.scenario.temperature_pattern is None and any(loaded):
            raise ValueError("climate inputs are not used with a deployment_pattern")
        if self.scenario.temperature_pattern is not None and not all(loaded):
            raise ValueError(
                "temperature_pattern needs cooling_per_forcing, lifetimes and temperature"
            )

        if self.scenario.temperature_pattern is None:
            return   # nothing below applies to an override run

        # Both are re-checked for every case in a sweep: with_overrides rebuilds
        # an Inputs per case, and dataclasses.replace re-runs __post_init__.
        if self.scenario.latitude not in self.cooling_per_forcing:
            raise ValueError(
                f"cannot inject at {self.scenario.latitude} degrees: climate.yaml gives "
                f"cooling_per_forcing only at {sorted(self.cooling_per_forcing)}"
            )
        if self.materials[self.scenario.deployed_material].forcing is None:
            raise ValueError(
                f"deployed_material {self.scenario.deployed_material!r} has no forcing "
                f"block in material.yaml, so its deployed mass cannot be derived"
            )

def read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"input file not found: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping (it may be empty or comments only)")
    return data

def check_years(df: pd.DataFrame, path: Path) -> None:
    """The checks every year-indexed input file shares.

    Such a file has to cover a solid block of years: a gap or a repeat means
    the model would quietly run a different schedule than the file describes.
    """
    if df.empty:
        raise ValueError(f"{path} has no data rows")
    if df.isna().any().any():
        raise ValueError(f"{path} has blank cells; every year needs a value in every column")

    years = df.index
    if years.min() < 2000 or years.max() > 2200:
        raise ValueError(
            f"{path} years must be between 2000 and 2200; got {years.min()}-{years.max()}"
        )
    if years.has_duplicates:
        raise ValueError(f"{path} repeats year(s) {sorted(years[years.duplicated()].unique())}")
    expected = pd.RangeIndex(years.min(), years.max() + 1)
    if not years.equals(expected):
        missing = sorted(set(expected) - set(years))
        raise ValueError(
            f"{path} years must be consecutive: "
            + (f"missing {missing}" if missing else "years are out of order")
        )


def check_pattern(df: pd.DataFrame, source: str | Path) -> pd.DataFrame:
    """Validate a deployment pattern in Tg/year and return it in kg/year.

    Both modes end here -- a hand-written CSV and the frame climatology derives
    -- so the two cannot drift apart on either the checks or the unit.
    """
    check_years(df, source)
    if (df < 0).any().any():
        raise ValueError(f"{source} has negative injection rates")
    return df * 1.0e9   # patterns are in Tg/year; the model works in kg

def load_pattern(filename: str, inputs_dir: Path = INPUTS_DIR) -> pd.DataFrame:
    """Read a deployment pattern CSV and convert it to kg per year."""
    path = inputs_dir / "scenario" / "deployment_patterns" / filename
    if not path.exists():
        raise FileNotFoundError(f"deployment pattern not found: {path}")

    df = pd.read_csv(path, index_col="year")
    df.index = df.index.astype(int)
    df.columns = df.columns.astype(int)
    df.index.name = "year"
    df.columns.name = "latitude"

    return check_pattern(df, path)


TEMPERATURE_COLUMNS = ["temperature_without_sai", "temperature_target"]


def load_temperature_pattern(filename: str, inputs_dir: Path = INPUTS_DIR) -> pd.DataFrame:
    """Read a temperature pattern CSV: warming expected, and warming wanted.

    Both columns are anomalies in degC against any consistent baseline. Only
    their difference is ever used, so which baseline does not matter, as long
    as both columns share one.
    """
    path = inputs_dir / "scenario" / "temperature_patterns" / filename
    if not path.exists():
        raise FileNotFoundError(f"temperature pattern not found: {path}")

    df = pd.read_csv(path, index_col="year")
    df.index = df.index.astype(int)
    df.index.name = "year"

    if list(df.columns) != TEMPERATURE_COLUMNS:
        raise ValueError(
            f"{path} must have columns year, {', '.join(TEMPERATURE_COLUMNS)}; "
            f"got year, {', '.join(map(str, df.columns))}"
        )

    check_years(df, path)

    # A year whose target sits above the warming expected without SAI needs no
    # deployment, which is the ordinary way a programme begins; climatology
    # clamps those to zero. But a file where no year needs cooling describes
    # nothing to model, and the usual cause is the columns being swapped.
    if not (df[TEMPERATURE_COLUMNS[0]] > df[TEMPERATURE_COLUMNS[1]]).any():
        raise ValueError(
            f"{path} never requires cooling: {TEMPERATURE_COLUMNS[1]} is at or above "
            f"{TEMPERATURE_COLUMNS[0]} in every year. Are the two columns swapped?"
        )

    return df

def load_lifetimes(
    filename: str, latitudes: list[int], inputs_dir: Path = INPUTS_DIR
) -> pd.DataFrame:
    """Read a stratospheric residence time table, in months.

    Indexed by (season, altitude) with latitude columns, so climatology can take
    one season or average across them. Months are kept: only the ratio to a
    material's forcing.reference_lifetime_months is used, and the units cancel.
    """
    path = inputs_dir / "stratospheric_lifetimes" / filename
    if not path.exists():
        raise FileNotFoundError(f"stratospheric lifetime table not found: {path}")

    df = pd.read_csv(path, index_col=["season", "altitude"])
    df.columns = df.columns.astype(int)     # read_csv gives '0', '15', ...; the grid is ints
    df.columns.name = "latitude"

    if list(df.columns) != sorted(latitudes):
        raise ValueError(
            f"{path} latitude columns {list(df.columns)} do not match "
            f"climate.yaml's cooling_per_forcing latitudes {sorted(latitudes)}"
        )

    seasons = df.index.get_level_values("season").unique()
    if len(seasons) != 2:
        raise ValueError(f"{path} needs exactly two seasons; got {list(seasons)}")
    grids = [df.loc[s] for s in seasons]
    if not grids[0].index.equals(grids[1].index):
        raise ValueError(f"{path} seasons cover different altitudes")
    if (df.dropna() <= 0).any().any():
        raise ValueError(f"{path} has residence times at or below zero")

    # A blank means the altitude is below the tropopause at that latitude, so
    # there is no stratospheric value to record. Climatology averages the two
    # seasons, and pandas skips NaN when it does, so a cell blank in one season
    # and filled in the other would quietly pass off one season as the annual
    # mean instead of failing.
    if not grids[0].isna().equals(grids[1].isna()):
        asymmetric = [(int(a), int(lat))
                      for a in grids[0].index for lat in df.columns
                      if grids[0].isna().loc[a, lat] != grids[1].isna().loc[a, lat]]
        raise ValueError(
            f"{path} is blank in one season but not the other at "
            f"(altitude, latitude) {asymmetric}"
        )

    return df


def load_inputs(inputs_dir: Path = INPUTS_DIR) -> Inputs:
    """Load and validate the full input set from disk.

    Each input file may carry a `sweepable:` list naming the variables in it a
    sweep may vary. Those lists are removed here, before the schemas see the
    data, and checked against the scenario's sweep block — this is the only
    place every input file is in scope at once.
    """
    scenario_data = read_yaml(inputs_dir / "scenario" / "scenario.yaml")
    sweepable = pop_sweepable("scenario", scenario_data)
    scenario = Scenario(**scenario_data)

    material_data = read_yaml(inputs_dir / "material.yaml")
    sweepable += pop_sweepable("material", material_data)

    method_data = read_yaml(
        inputs_dir / "deployment_methods" / f"{scenario.deployment_method}.yaml"
    )
    sweepable += pop_sweepable("method", method_data)

    for name in scenario.sweep:
        if name not in sweepable:
            raise ValueError(
                f"cannot sweep {name!r}: no input file declares it sweepable. "
                f"Sweepable: {', '.join(sweepable)}"
            )

    if scenario.deployment_pattern is not None:
        pattern = load_pattern(scenario.deployment_pattern, inputs_dir)
    else:
        climate = Climate(**read_yaml(inputs_dir / "climate.yaml"))
        cooling_per_forcing = climate.cooling_per_forcing
        lifetimes = load_lifetimes(
            climate.stratospheric_lifetimes, list(cooling_per_forcing), inputs_dir
        )
        temperature = load_temperature_pattern(scenario.temperature_pattern, inputs_dir)
        raise NotImplementedError(
            "temperature_pattern needs the climatology module, which does not exist yet"
        )


    return Inputs(
        scenario=scenario,
        materials={k: Material(**v) for k, v in material_data.items()},
        currency_year=read_yaml(inputs_dir / "finance.yaml")["currency_year"],
        pattern=pattern,
        method=method_data,
        inputs_dir=inputs_dir,
    )


def set_at(data: dict[str, Any], path: str, value: Any) -> None:
    """Set the value at dotted `path` inside a nested dict, in place.

    `path` is a chain of keys joined by dots -- the same spelling the sweepable
    lists use. Setting "forcing.per_mass" to 2e-10 in

        {"cost": 0.2, "forcing": {"per_mass": 1e-10, "source": "..."}}

    reaches into data["forcing"] and sets its "per_mass" key, leaving "cost"
    and "source" untouched.

    Nothing is copied first: both callers already hold a dict nobody else has
    -- one from model_dump(), one freshly re-read from file -- so writing into
    it cannot affect anything outside.
    """
    keys = path.split(".")        # "forcing.per_mass" -> ["forcing", "per_mass"]

    # Step down one key at a time until `node` is the dict holding the last
    # key. For a one-level path like "cost" this loop runs zero times and
    # `node` stays `data` itself.
    node = data
    for key in keys[:-1]:         # every key except the last one
        node = node[key]

    # `node` is a dict inside `data`, not a copy of one, so assigning through
    # it changes `data`. That is why this function returns nothing.
    node[keys[-1]] = value        # the last key



def with_overrides(base: Inputs, overrides: dict[str, Any]) -> Inputs:
    """Rebuild `base` with overrides applied, re-running validation.

    Overrides are the namespaced paths a sweep block names, so each one is
    routed to the part of the input set that owns it. Scenario and material
    values go back through their constructors rather than being assigned, so a
    swept value gets the same checks a hand-written one would; method values
    land in a raw dict and are checked later by the method module that owns it.
    """
    by_root: dict[str, dict[str, Any]] = {"scenario": {}, "material": {}, "method": {}}
    for path, value in overrides.items():
        root, _, rest = path.partition(".")
        if root not in by_root:
            raise ValueError(
                f"override {path!r} must start with scenario., material. or method."
            )
        by_root[root][rest] = value

    scenario = Scenario(**{**base.scenario.model_dump(), **by_root["scenario"]})

    # A material override names a path inside one material, like
    # "SO2.forcing.per_mass": the first key picks the material and the rest is
    # a path within it. model_dump() hands back a plain nested dict to edit,
    # and rebuilding the Material from it re-runs the schema's validation.
    materials = base.materials
    for path, value in by_root["material"].items():
        name, _, rest = path.partition(".")
        data = materials[name].model_dump()
        set_at(data, rest, value)
        materials = {**materials, name: Material(**data)}

    # A method override needs somewhere safe to land: base.method is shared by
    # every case in the sweep, so re-read the file to get a dict nobody else
    # holds. A fresh read still carries the sweepable list its schema forbids.
    method = base.method
    if by_root["method"] or scenario.deployment_method != base.scenario.deployment_method:
        method = read_yaml(
            base.inputs_dir / "deployment_methods" / f"{scenario.deployment_method}.yaml"
        )
        pop_sweepable("method", method)
    for path, value in by_root["method"].items():
        set_at(method, path, value)

    pattern = base.pattern
    if (scenario.deployment_pattern is not None
        and scenario.deployment_pattern != base.scenario.deployment_pattern):
        pattern = load_pattern(scenario.deployment_pattern, base.inputs_dir)

    return replace(base, scenario=scenario, materials=materials,
                   method=method, pattern=pattern)


def pop_sweepable(namespace: str, data: dict[str, Any]) -> list[str]:
    """Remove `data`'s `sweepable:` list and return its paths, namespaced.

    Removes rather than reads: the schemas that validate these files forbid
    unknown keys, so `sweepable` has to be gone before they see the data.
    Paths are relative to their own file going in and namespaced coming out,
    so `unit.cost` in teleporter.yaml becomes `method.unit.cost`.

    Called by load_inputs to check the sweep block, and by docs/app.py to fill
    the GUI's parameter list.
    """
    return [f"{namespace}.{name}" for name in data.pop("sweepable", [])]