"""Reading and validating CIIM input files.

The only module that touches the filesystem. Everything downstream receives
validated, immutable objects, which is what lets the model run from the command
line, from a notebook, or from a GUI.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

import math

from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

# default input directory, defined relative to current file location
INPUTS_DIR = Path(__file__).resolve().parent / "inputs"


# Pydantic schemas, one per input file shape. Validation runs on construction,
# so a bad value fails here rather than surfacing as a wrong number later.


class Frozen(BaseModel):
    """Shared settings for every schema: immutable, and an unknown key is an error."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class Material(Frozen):
    """One entry in material.yaml."""

    cost: float = Field(ge=0, description="USD per kg of this material")
    source: str = Field(description="Where the cost figure came from")
    molar_mass: float | None = Field(default=None, gt=0, lt=1, description="kg/mol")


class SweepRange(Frozen):
    """An inclusive start/stop/step range of values for one swept parameter."""

    start: float
    stop: float
    step: float = Field(gt=0)

    @model_validator(mode="after")
    def stop_at_or_above_start(self) -> SweepRange: # error check in case parameter sweep starts after it stops
        if self.stop < self.start:
            raise ValueError(f"sweep stop ({self.stop}) is below start ({self.start})")
        return self

    @model_validator(mode="after")
    def step_divides_span(self) -> SweepRange: # error check
        """The span must be a whole number of steps, or the sweep isn't the one asked for.

        values() spaces its points evenly between start and stop, so a span that is
        not a whole multiple of step comes back with a different spacing than the
        YAML requested — silently.
        """
        span = self.stop - self.start
        n_steps = round(span / self.step)
        if not math.isclose(n_steps * self.step, span, rel_tol=1e-9): # a little bit of tolerance here in case of slight discrepancies in float numbers
            landed = self.start + n_steps * self.step
            raise ValueError(
                f"sweep step {self.step:g} does not divide {self.start:g}..{self.stop:g} "
                f"a whole number of times ({span / self.step:.6g} steps). "
                f"Set stop to {landed:g}, or pick a step that divides {span:g}."
            )
        return self

    
    def values(self) -> list[float]:
        """Endpoint-exact values, generated by count rather than accumulation.

        Assumes step_divides_span has passed.
        """
        n = round((self.stop - self.start) / self.step) + 1
        if n == 1:
            return [self.start]
        return [self.start + i * (self.stop - self.start) / (n - 1) for i in range(n)]


class Scenario(Frozen):
    """scenario.yaml: what the model is being asked to do."""

    deployment_method: str
    deployment_pattern: str
    deployed_material: str
    altitude: float = Field(gt=0, description="Injection altitude, metres")
    sweep: dict[str, SweepRange] = Field(default_factory=dict)
    # Numeric ranges only for now. Sweeping deployment_method or
    # deployment_pattern needs a list of strings, i.e. SweepRange | list[...].
    
    @model_validator(mode="after")
    def sweep_targets_exist(self) -> Scenario: # function to determine sweepable parameters in scenario
        sweepable = set(type(self).model_fields) - {"sweep"}
        for key in self.sweep:
            if key not in sweepable:
                raise ValueError(
                    f"cannot sweep {key!r}: not a scenario parameter. "
                    f"Sweepable: {', '.join(sorted(sweepable))}"
                )
        return self


    




@dataclass(frozen=True)
class Inputs:
    """Everything one model run needs, as a single value."""

    scenario: Scenario
    materials: dict[str, Material]
    currency_year: int
    pattern: pd.DataFrame        # kg/year, indexed by year, columns are latitudes
    method: dict[str, Any]       # raw method YAML; the method module validates it
    inputs_dir: Path             # where this set was loaded from

    def __post_init__(self) -> None:
        if self.scenario.deployed_material not in self.materials:
            raise ValueError(
                f"deployed_material {self.scenario.deployed_material!r} is not in "
                f"material.yaml. Known materials: {', '.join(sorted(self.materials))}"
            )


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"input file not found: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping (it may be empty or comments only)")
    return data


def load_pattern(filename: str, inputs_dir: Path = INPUTS_DIR) -> pd.DataFrame:
    """Read a deployment pattern CSV and convert it to kg per year."""
    path = inputs_dir / "scenario" / "deployment_patterns" / filename
    if not path.exists():
        raise FileNotFoundError(f"deployment pattern not found: {path}")

    df = pd.read_csv(path, index_col="year")
    df.index = df.index.astype(int)
    df.columns = df.columns.astype(int)
    df.index.name = "year"
    df.columns.name = "latitude"

    # error checking for deplyoment pattern file

    if df.empty:
        raise ValueError(f"{path} has no data rows")
    if df.isna().any().any():
        raise ValueError(f"{path} has blank cells; every year and latitude needs a value")
    if (df < 0).any().any():
        raise ValueError(f"{path} has negative injection rates")

    years = df.index
    if years.min() < 2000 or years.max() > 2200:
        raise ValueError(
            f"{path} years must be between 2000 and 2200; got {years.min()}-{years.max()}"
        )
    if years.has_duplicates:
        raise ValueError(f"{path} repeats year(s) {sorted(years[years.duplicated()].unique())}")
    expected = pd.RangeIndex(years.min(), years.max() + 1)
    if not years.equals(expected):
        missing = sorted(set(expected) - set(years))
        raise ValueError(
            f"{path} years must be consecutive: "
            + (f"missing {missing}" if missing else "years are out of order")
        )
    return df * 1.0e9   # pattern CSVs are Tg/year; the model works in kg


def load_inputs(inputs_dir: Path = INPUTS_DIR) -> Inputs:
    """Load and validate the full input set from disk."""
    scenario = Scenario(**read_yaml(inputs_dir / "scenario" / "scenario.yaml"))
    return Inputs(
        scenario=scenario,
        materials={k: Material(**v) for k, v in read_yaml(inputs_dir / "material.yaml").items()},
        currency_year=read_yaml(inputs_dir / "finance.yaml")["currency_year"],
        pattern=load_pattern(scenario.deployment_pattern, inputs_dir),
        method=read_yaml(
            inputs_dir / "deployment_methods" / f"{scenario.deployment_method}.yaml"
        ),
        inputs_dir=inputs_dir,
    )


def with_overrides(base: Inputs, overrides: dict[str, Any]) -> Inputs:
    """Rebuild `base` with scenario overrides applied, re-running validation.
    Overrides go through the Scenario constructor rather than mutating anything,
    so a swept value gets the same checks a hand-written one would. Only the
    files an override actually changed are re-read.
    """
    scenario = Scenario(**{**base.scenario.model_dump(), **overrides})

    method = base.method
    if scenario.deployment_method != base.scenario.deployment_method:
        method = read_yaml(
            base.inputs_dir / "deployment_methods" / f"{scenario.deployment_method}.yaml"
        )

    pattern = base.pattern
    if scenario.deployment_pattern != base.scenario.deployment_pattern:
        pattern = load_pattern(scenario.deployment_pattern, base.inputs_dir)

    return replace(base, scenario=scenario, method=method, pattern=pattern)